"""
Contains functionality for handling outputs of HCIE searches.
"""

import os
import csv
from datetime import datetime
from typing import Optional

from rdkit import Chem
from rdkit.Chem import Draw, AllChem


def new_directory(func):
    def wrapper(*args, **kwargs):
        # Save the current working directory
        current_dir = os.getcwd()

        output_dir = kwargs.get("output_dir")
        if output_dir:
            new_dir = output_dir
        elif "query_name" in kwargs:
            new_dir = f'{kwargs["query_name"]}_hcie_results'
        else:
            new_dir = "hcie_results"

        new_dir = os.path.abspath(new_dir)

        try:
            # Create the new directory if it doesn't exist
            os.makedirs(new_dir, exist_ok=True)

            # Change the working directory to the new directory
            os.chdir(new_dir)

            # Call the wrapped function
            result = func(*args, **kwargs)
            return result
        finally:
            # Change back to the previous directory after the function finishes
            os.chdir(current_dir)

    return wrapper


@new_directory
def print_results(
    mol_dict: dict,
    results: list,
    query_smiles: str,
    query_name: str,
    output_dir: Optional[str] = None,
) -> None:
    """
    Prints out the results of a search against a database.
    :param mol_dict:
    :param results:
    :param query_smiles:
    :param query_name:
    :return:
    """
    current_datetime = datetime.now()
    filename = f"{query_name}_results.csv"
    query_props = mol_dict["query"].phys_chem_props

    with open(filename, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)

        # Metadata rows
        writer.writerow(
            ["Generated by HCIE:", current_datetime.strftime("%H:%M, %d/%m/%Y")]
        )
        writer.writerow(["Query molecule:", query_name])
        writer.writerow(["Query SMILES:", query_smiles])

        writer.writerow(
            [
                "MW",
                "cLogP",
                "total polar surface area (TPSA)",
                "hydrogen bond donors (HBD)",
                "hydrogen bond acceptors (HBA)",
                "heavy atoms",
                "heteroatoms",
            ]
        )
        prop_keys = ["MW", "cLogP", "TPSA", "HBD", "HBA", "HeavyAtoms", "Heteroatoms"]
        query_props_list = [query_props[k] for k in prop_keys]

        writer.writerow(query_props_list)
        writer.writerow([])  # blank line before table starts

        # Header row
        writer.writerow(
            [
                "Rank",
                "RegID",
                "SMILES",
                "Score",
                "ESP Score",
                "Shape Score",
                "Delta_MW",
                "Delta_cLogP",
                "Delta_TPSA",
                "Delta_HBD",
                "Delta_HBA",
                "Delta_Heavy atoms",
                "Delta_Heteroatoms",
                "Conformer ID",
            ]
        )

        for rank, result in enumerate(results):
            regid, score, conf_id, esp_score, shape_score, smiles = (
                str(result[0]),
                float(result[1]),
                int(result[4]),
                float(result[3]),
                float(result[2]),
                result[-1],
            )

            # RDKit insists on putting dummy atoms in SMILES that aren't recognised by ChemDraw, so these need replacing
            smiles = smiles.replace("[*:1]", "[R1]").replace("[*:2]", "[R2]")

            # Calculate the deltas (difference between query and probe) for the physicochemical properties
            deltas = {
                prop: mol_dict[regid].phys_chem_props[prop] - query_props[prop]
                for prop in prop_keys
            }

            writer.writerow(
                [
                    rank,
                    regid,
                    smiles,
                    f"{score:.2f}",
                    f"{esp_score:.2f}",
                    f"{shape_score:.2f}",
                    f"{deltas['MW']:.1f}",
                    f"{deltas['cLogP']:.2f}",
                    f"{deltas['TPSA']:.2f}",
                    int(deltas["HBD"]),
                    int(deltas["HBA"]),
                    int(deltas["HeavyAtoms"]),
                    int(deltas["Heteroatoms"]),
                    conf_id,
                ]
            )

    return None


@new_directory
def alignments_to_sdf(
    results: list,
    mol_alignments: dict,
    query_name: str,
    num_of_mols: int = 50,
    output_dir: Optional[str] = None,
) -> None:
    """

    :param results:
    :param mol_alignments:
    :param query_name:
    :param num_of_mols:
    :return:
    """
    filename = f"{query_name}_aligned_results.sdf"

    with Chem.SDWriter(filename) as writer:
        # Write out the query molecule
        query = mol_alignments["query"]
        query.mol.SetProp("_Name", "Query")
        writer.write(query.mol)

        # Write the aligned result mols to the SD file
        for result in results[:num_of_mols]:
            mol = mol_alignments[result[0]]
            mol.mol.SetProp("_Name", f"{result[0]}")
            mol.mol.SetProp("total_score", f"{result[1]}")
            mol.mol.SetProp("ESP_score", f"{result[3]}")
            mol.mol.SetProp("shape_score", f"{result[2]}")
            writer.write(mol.mol, confId=int(result[4]))

    return None


@new_directory
def mols_to_image(
    results: list,
    query_name: str,
    num_of_mols: int = 50,
    output_dir: Optional[str] = None,
):
    """

    :param results:
    :param query_name:
    :param num_of_mols:
    :return:
    """
    mols_to_draw = [Chem.MolFromSmiles(result[-1]) for result in results[:num_of_mols]]
    keys = [
        f"{result[0]}\n\nTotal Score: {result[1]:.2f}"
        for result in results[:num_of_mols]
    ]
    img = Draw.MolsToGridImage(
        mols_to_draw, subImgSize=(300, 250), molsPerRow=5, legends=keys, returnPNG=False
    )
    img.save(f"{query_name}_results.png")

    return None
